"""Shell, file, and dev-server tool nodes."""

import json
import shlex
from datetime import date

from langchain_core.messages import SystemMessage, HumanMessage

from src.tools.registry import (
    shell_command_tool, write_file_tool, delete_file_tool, start_dev_server_tool,
)
from src.agents.prompts.loader import load_prompt
from .common import _pkg
from ..state import State, StepStatus
from .common import _build_coding_context

def shell_node(state: State) -> dict:
    """
    Execute a shell command step (tool_hint='shell_command').

    Asks the LLM to produce the exact shell command to run for this step,
    then runs it via shell_command_tool inside the project workspace.
    The LLM receives the full goal, prior results, and the workspace path
    so it can construct the correct command (e.g. correct project root).
    """
    plan = state["plan"]
    if plan is None:
        raise RuntimeError("shell_node called with no plan in state")

    current_step = next((s for s in plan.subtasks if s.status == StepStatus.RUNNING), None)
    if current_step is None:
        raise RuntimeError("shell_node called with no RUNNING step")

    workspace_path = state.get("workspace_path") or ""
    if not workspace_path:
        current_step.status = StepStatus.FAILED
        current_step.error = (
            "shell_node: no workspace_path in state. "
            "Ensure a setup_workspace step runs before any shell_command step."
        )
        return {"plan": plan, "steps_executed": 1}

    context_block = _build_coding_context(plan, current_step)

    command_prompt = load_prompt("plan_execute", "shell_command").format(**locals())

    llm = _pkg().get_llm()
    messages = [
        SystemMessage(content=load_prompt("plan_execute", "shell_command_system")),
        HumanMessage(content=command_prompt),
    ]

    try:
        # Check if command was pre-generated by approval_node
        if current_step.result and current_step.result.startswith("_PENDING_COMMAND:"):
            command = current_step.result.replace("_PENDING_COMMAND: ", "")
        else:
            response = llm.invoke(messages)
            command = response.content.strip()
            # Strip any accidental markdown fences the LLM might add
            if command.startswith("```"):
                lines = command.split("\n")
                command = "\n".join(
                    line for line in lines if not line.startswith("```")
                ).strip()

        # --- Guard: refuse to run long-running server commands here ---
        # shell_command_tool / run_shell_command blocks until the process
        # exits (that's correct for one-shot commands like npm install).
        # A dev server never exits on its own, so routing one here — via a
        # planner or replanner mistake — hangs the whole graph indefinitely
        # instead of failing. This has happened in practice (replanner
        # generating "npm run dev" as a shell_command "diagnostic" step
        # after a start_server failure). Catch it here as a deterministic
        # backstop in addition to the prompt-level guidance in
        # REPLAN_INSTRUCTIONS, since an LLM instruction is best-effort and
        # this failure mode hangs the CLI rather than just producing a
        # wrong answer — worth the extra certainty of a code-level check.
        #
        # IMPORTANT: match against tokenized words, not a raw substring
        # search on the whole command string. A substring check on "vite"
        # false-positives on "create-vite" (a normal one-shot scaffold
        # command, not a server start) — tokenizing avoids that class of
        # false positive entirely.
        try:
            command_tokens = [t.lower() for t in shlex.split(command)]
        except ValueError:
            command_tokens = command.lower().split()

        looks_like_server_start = (
            "vite" in command_tokens
            or "dev" in command_tokens  # e.g. "npm run dev", "next dev"
            or "start" in command_tokens  # e.g. "npm start"
            or "runserver" in command_tokens
            or "uvicorn" in command_tokens
            or ("-m" in command_tokens and "http.server" in command_tokens)
            or ("flask" in command_tokens and "run" in command_tokens)
        ) and not any(t in command_tokens for t in ("install", "build", "--version", "-v"))

        if looks_like_server_start:
            current_step.status = StepStatus.FAILED
            current_step.error = (
                f"REFUSED: '{command}' looks like a command that starts a "
                "long-running dev server. shell_command cannot run this — it "
                "blocks until the process exits, and a dev server never "
                "exits on its own, so this would hang indefinitely. Use "
                "tool_hint 'start_server' instead, which runs the process "
                "correctly (non-blocking, with a port-open timeout and "
                "stderr capture)."
            )
            current_step.result = f"Command attempted (refused): {command}"
            print(f"❌ Shell command refused (looks like server start): {command}")
            return {"plan": plan, "steps_executed": 1}

        result_str = shell_command_tool(command, workspace_path)

        if result_str.startswith("ERROR:"):
            current_step.status = StepStatus.FAILED
            current_step.error = result_str
            current_step.result = f"Command attempted: {command}\n{result_str}"
            print(f"❌ Shell command failed: {result_str[:200]}")
        else:
            current_step.status = StepStatus.DONE
            current_step.result = f"$ {command}\n{result_str}"
            print(f"✅ Shell command completed")
            print(f"👁️  Result: {result_str[:300]}{'...' if len(result_str) > 300 else ''}")

    except Exception as e:
        current_step.status = StepStatus.FAILED
        current_step.error = f"shell_node error: {str(e)}"
        print(f"❌ Shell command error: {str(e)}")

    return {"plan": plan, "steps_executed": 1}


def write_file_node(state: State) -> dict:
    """
    Generate and write a source code file (tool_hint='write_file' or 'file_editor').

    The LLM generates the complete file content for the requested file. The
    node writes it to disk inside the project workspace via write_file_tool.
    """
    plan = state["plan"]
    if plan is None:
        raise RuntimeError("write_file_node called with no plan in state")

    current_step = next((s for s in plan.subtasks if s.status == StepStatus.RUNNING), None)
    if current_step is None:
        raise RuntimeError("write_file_node called with no RUNNING step")

    workspace_path = state.get("workspace_path") or ""
    if not workspace_path:
        current_step.status = StepStatus.FAILED
        current_step.error = (
            "write_file_node: no workspace_path in state. "
            "Ensure a setup_workspace step runs before any write_file step."
        )
        return {"plan": plan, "steps_executed": 1}

    context_block = _build_coding_context(plan, current_step)
    today = date.today().isoformat()

    file_prompt = load_prompt("plan_execute", "write_file").format(**locals())

    llm = _pkg().get_llm()
    messages = [
        SystemMessage(content=load_prompt("plan_execute", "write_file_system")),
        HumanMessage(content=file_prompt),
    ]

    try:
        import json

        # Check if file path was pre-generated by approval_node
        if current_step.result and current_step.result.startswith("_PENDING_FILE_PATH:"):
            rel_path = current_step.result.replace("_PENDING_FILE_PATH: ", "")
            # Generate content after approval
            content_prompt = load_prompt("plan_execute", "write_file_content").format(**locals())

            llm = _pkg().get_llm()
            messages = [
                SystemMessage(content=load_prompt("plan_execute", "write_file_content_system")),
                HumanMessage(content=content_prompt),
            ]
            response = llm.invoke(messages)
            raw = response.content.strip()
            if raw.startswith("```"):
                lines = raw.split("\n")
                raw = "\n".join(line for line in lines if not line.startswith("```")).strip()
            data = json.loads(raw)
            content = data.get("content", "")
        else:
            response = llm.invoke(messages)
            raw = response.content.strip()

            # Strip markdown fences if present
            if raw.startswith("```"):
                lines = raw.split("\n")
                raw = "\n".join(line for line in lines if not line.startswith("```")).strip()

            data = json.loads(raw)
            rel_path = data.get("path", "")
            content = data.get("content", "")

        if not rel_path:
            current_step.status = StepStatus.FAILED
            current_step.error = "write_file_node: LLM returned empty 'path'"
            return {"plan": plan, "steps_executed": 1}

        result_str = write_file_tool(rel_path, content, workspace_path)

        if result_str.startswith("ERROR:"):
            current_step.status = StepStatus.FAILED
            current_step.error = result_str
            print(f"❌ Write file failed: {result_str[:200]}")
        else:
            current_step.status = StepStatus.DONE
            current_step.result = f"{result_str}\nPath: {rel_path}"
            print(f"✅ File written: {rel_path}")
            print(f"👁️  Result: {result_str[:200]}")

    except json.JSONDecodeError as e:
        current_step.status = StepStatus.FAILED
        current_step.error = f"write_file_node: LLM returned invalid JSON: {e}"
        print(f"❌ Write file JSON error: {e}")
    except Exception as e:
        current_step.status = StepStatus.FAILED
        current_step.error = f"write_file_node error: {str(e)}"
        print(f"❌ Write file error: {str(e)}")

    return {"plan": plan, "steps_executed": 1}


def delete_file_node(state: State) -> dict:
    """
    Delete a file, directory, or clear the workspace (tool_hint='delete_file').

    Exists so steps like "delete all files in the project" have a real,
    safe path to succeed. Without this node, the executor's only option
    was shell_command with 'rm', which is intentionally blocked by
    ALLOWED_COMMANDS — every such step previously failed and forced a
    replan, and the replanner had no better alternative to reach for,
    so it thrashed through several blocked variants (rm, rm -rf *, a
    python+shutil one-liner that also failed since the sandbox's python
    binary isn't 'python') before hitting the replan cap and giving up.
    See agent_outputs/20260720-025417_.../plan.json and
    agent_outputs/20260720-121944_.../ for two reproduced instances.

    The LLM only needs to specify WHICH path to clear, not generate any
    content — much simpler than write_file_node.
    """
    plan = state["plan"]
    if plan is None:
        raise RuntimeError("delete_file_node called with no plan in state")

    current_step = next((s for s in plan.subtasks if s.status == StepStatus.RUNNING), None)
    if current_step is None:
        raise RuntimeError("delete_file_node called with no RUNNING step")

    workspace_path = state.get("workspace_path") or ""
    if not workspace_path:
        current_step.status = StepStatus.FAILED
        current_step.error = (
            "delete_file_node: no workspace_path in state. "
            "Ensure a setup_workspace step runs before any delete_file step."
        )
        return {"plan": plan, "steps_executed": 1}

    context_block = _build_coding_context(plan, current_step)
    today = date.today().isoformat()

    delete_prompt = load_prompt("plan_execute", "delete_file").format(**locals())

    llm = _pkg().get_llm()
    messages = [
        SystemMessage(content=load_prompt("plan_execute", "delete_file_system")),
        HumanMessage(content=delete_prompt),
    ]

    try:
        import json

        # Check if path was pre-generated by approval_node
        if current_step.result and current_step.result.startswith("_PENDING_PATH:"):
            rel_path = current_step.result.replace("_PENDING_PATH: ", "")
        else:
            response = llm.invoke(messages)
            raw = response.content.strip()

            if raw.startswith("```"):
                lines = raw.split("\n")
                raw = "\n".join(line for line in lines if not line.startswith("```")).strip()

            data = json.loads(raw)
            rel_path = data.get("path", "")

        result_str = delete_file_tool(rel_path, workspace_path)

        if result_str.startswith("ERROR:"):
            current_step.status = StepStatus.FAILED
            current_step.error = result_str
            print(f"❌ Delete failed: {result_str[:200]}")
        else:
            current_step.status = StepStatus.DONE
            current_step.result = result_str
            print(f"✅ {result_str}")

    except json.JSONDecodeError as e:
        current_step.status = StepStatus.FAILED
        current_step.error = f"delete_file_node: LLM returned invalid JSON: {e}"
        print(f"❌ Delete JSON error: {e}")
    except Exception as e:
        current_step.status = StepStatus.FAILED
        current_step.error = f"delete_file_node error: {str(e)}"
        print(f"❌ Delete error: {str(e)}")

    return {"plan": plan, "steps_executed": 1}


def start_server_node(state: State) -> dict:
    """
    Start a dev server and store its URL in state (tool_hint='start_server').

    Asks the LLM which command and port to use based on the project type
    (detected from prior step results), then starts the server via
    start_dev_server_tool. The URL is stored in state["server_url"] so
    synthesize_node can surface it in the final answer.
    """
    plan = state["plan"]
    if plan is None:
        raise RuntimeError("start_server_node called with no plan in state")

    current_step = next((s for s in plan.subtasks if s.status == StepStatus.RUNNING), None)
    if current_step is None:
        raise RuntimeError("start_server_node called with no RUNNING step")

    workspace_path = state.get("workspace_path") or ""
    if not workspace_path:
        current_step.status = StepStatus.FAILED
        current_step.error = (
            "start_server_node: no workspace_path in state. "
            "Ensure a setup_workspace step runs before start_server."
        )
        return {"plan": plan, "steps_executed": 1}

    context_block = _build_coding_context(plan, current_step)

    server_prompt = load_prompt("plan_execute", "start_server").format(**locals())

    llm = _pkg().get_llm()
    messages = [
        SystemMessage(content=load_prompt("plan_execute", "start_server_system")),
        HumanMessage(content=server_prompt),
    ]

    try:
        import json

        response = llm.invoke(messages)
        raw = response.content.strip()

        if raw.startswith("```"):
            lines = raw.split("\n")
            raw = "\n".join(line for line in lines if not line.startswith("```")).strip()

        data = json.loads(raw)
        command = data.get("command", "npm run dev")
        port = int(data.get("port", 5173))

        url_or_error = start_dev_server_tool(command, workspace_path, port)

        if url_or_error.startswith("ERROR:"):
            current_step.status = StepStatus.FAILED
            current_step.error = url_or_error
            print(f"❌ Dev server failed: {url_or_error[:200]}")
            return {"plan": plan, "steps_executed": 1}

        # Success — record the URL
        current_step.status = StepStatus.DONE
        current_step.result = (
            f"✅ Dev server running at {url_or_error}\n"
            f"Command: {command}\nPort: {port}\nWorkspace: {workspace_path}"
        )
        print(f"✅ Dev server started at {url_or_error}")
        print(f"👁️  Command: {command}, Port: {port}")
        return {"plan": plan, "steps_executed": 1, "server_url": url_or_error}

    except json.JSONDecodeError as e:
        current_step.status = StepStatus.FAILED
        current_step.error = f"start_server_node: LLM returned invalid JSON: {e}"
        print(f"❌ Dev server JSON error: {e}")
    except Exception as e:
        current_step.status = StepStatus.FAILED
        current_step.error = f"start_server_node error: {str(e)}"
        print(f"❌ Dev server error: {str(e)}")

    return {"plan": plan, "steps_executed": 1}
